spring:
  datasource:
    username: root
    password: ac2015
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G73Dewcd8U5pC1dppWk
      secret-key: MSDVelqAqDtk9RW18ftGMrhC5TKzxs
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000

