spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFfDn61sba5WQXeHptA
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-adverseq
      sms:
        accessKeyId: LTAI4G73Dewcd8U5pC1dppWk
        secret:
        templateCode: SMS_189520818
        signName: 谷粒商城

  application:
    name: gulimall-third-party

server:
  port: 30000
